spring.application.name=task-manager-api
spring.data.mongodb.uri=mongodb+srv://admin:Admin1234@taskmanager.v43nxkp.mongodb.net/taskmanager?retryWrites=true&w=majority
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
